[#45] Agregada verificacion al login
frontendcafe/sunrise-cafe pull request #48
Opened 2024-02-29 02:06 UTC by Durphan

- Agregada verificacion a la login page utilizando RegExp
- Agregado dos props al Button primary
- Cambio en el estilo del logo del login
- Fixeo de la llamada a una funcion en Order

2024-03-02 18:22 UTC, brahianpdev commented on .vscode/settings.json
> +    "source.fixAll.eslint": "explicit"
Es necesario cambie esta regla?

2024-03-02 18:24 UTC, brahianpdev commented on package-lock.json
Existen muchos cambios en el package-lock, estos a qué se deben?

2024-03-02 18:26 UTC, brahianpdev commented on src/atoms/CoffeeBanner.jsx
> +  justify-content: center;
Podemos agregar a la descripción del PR, una captura de la web **antes - después** de este cambio?

2024-03-02 18:27 UTC, brahianpdev commented on src/molecules/ChoosePayment.jsx
> +    console.log("payment")
El `console.log` nos servira en el dia a dia de desarrollo, pero no deberia estar en produccion, podemos tambien dejarle asociado in TODO, para darle funcionalidad a dicho handle.

```js
// TODO: ISSUE-01 Crear funcionalidad para elegir el método de pago al hacer click.
console.log("payment")
```

2024-03-02 18:28 UTC, Durphan commented on .vscode/settings.json
> +    "source.fixAll.eslint": "explicit"
Buenas, ese cambio de regla fue debido a que la configuracion de Visual Studio cambio a partir de la version 1.85.0 y Visual Studio Code, cambia automaticamente esa configuracion a "Explicit", por lo que esa propiedad no puede recibir booleanos como lo hacia en versiones anteriores.

Source: https://stackoverflow.com/questions/77637621/vscode-workspace-settings-change-on-its-own

2024-03-02 18:29 UTC, brahianpdev commented on src/molecules/LoginForm.jsx
> +      console.log("El email debe contener un @ y .com");
Quizás en este punto deberíamos retornar un String, para poder renderizar dicho mensaje de cara al usuario en lugar de sólo verlo por consola.

2024-03-02 18:31 UTC, brahianpdev commented on src/molecules/LoginForm.jsx
> +    const passwordRegex = /[0-9]/;
Podriamos utilizar una rgx, que haga todo lo que se valida en los ifs, entonces tenemos una función más limpia:
```
^(?=.*[0-9]).{5,}$
```
Entonces, si la password no coincide con el patrón, le retornamos el mensaje al usuario para que vuelva a ingresar la contraseña hasta que sea válida

2024-03-09 22:05 UTC, brahianpdev commented on src/molecules/LoginForm.jsx
> +      setEmailError(``);
setEmailError, y setPasswordError, existen?

2024-03-21 21:35 UTC, JoeOsG reviewed
Listo.

2024-03-21 21:35 UTC, JoeOsG commented on src/atoms/p.js
> +export const ErrorP = styled.p`
Aquí me parece que quedaría claro que el atomo tenga un nombre descriptivo. I.E. Paragraph.

2024-03-21 21:35 UTC, JoeOsG commented on src/molecules/Header.jsx
> +  justify-content: space-around;
En lugar de mover la justificación de contenido, probar con el padding para acercarse mas al diseño.

2024-03-21 21:36 UTC, JoeOsG submitted a review, later dismissed

2024-03-21 22:54 UTC, brahianpdev approved these changes

2024-03-22 01:48 UTC, rolivencia requested changes

2024-03-22 01:48 UTC, rolivencia commented on src/atoms/CoffeeBanner.jsx
> +  // justify-content: space-between;
Lo que no va se borra, para archivo está el log de git.

2024-03-22 01:48 UTC, rolivencia commented on src/molecules/ChoosePayment.jsx
> +    console.log('payment');
No debe hacerse commit de los `console.log`. Si una función debe ser implementada, dejar un comentario o tirar una excepción.

2024-03-22 01:48 UTC, rolivencia commented on src/molecules/TopMenu.jsx
> +  // justify-content: space-between;
Ídem más arriba: no hacer commit de comentarios de cambios estructurales.

2024-03-22 01:48 UTC, rolivencia commented on src/styles/colors.js
> +  rojo: `#fc0339`,
¿Los colores están definidos en ambos idiomas? Creo que deberíamos de unificarlos a todos en inglés.

2024-11-27 01:15 UTC, sarganar commented on src/molecules/LoginForm.jsx
> +      setEmailError(``);
Al parecer son setters de estados del componente.

2024-11-27 01:16 UTC, sarganar commented on src/styles/colors.js
> +  secondary: '#F2E6D8',
Creo que aquí debería conservarse el nombre referncial del color, aunque en inglés.

2024-12-23 20:16 UTC, sarganar submitted a review, later dismissed
I touched _ChoosePayment.jsx_ to eliminate the use of consolo.log

2024-12-24 23:47 UTC, JoeOsG submitted a review, later dismissed
### **Good**

2024-12-24 23:56 UTC, JoeOsG commented on src/atoms/CoffeeBanner.jsx
> +  justify-content: center;
No entiendo Brahian. 
¿Qué se explique este cambio pides?

2024-12-24 23:56 UTC, JoeOsG commented on package-lock.json
Creo que esto es a que no tenemos restricción de versión, por lo tanto se va actualizando de manera automática.

2025-04-10 22:12 UTC, sarganar commented
Perdón la consulta, creo que este PR no se mergeó a la rama principal. Es así?

2025-04-11 02:04 UTC, Durphan commented
> Perdón la consulta, creo que este PR no se mergeó a la rama principal. Es así?

Hola Sarganar, no, no esta mergeado todavia, lo cerre sin percatarme de ello y ahi lo vuelvo abrir

2025-04-26 16:40 UTC, rolivencia approved these changes

2025-04-26 16:42 UTC, JoeOsG approved these changes

2025-04-26 16:42 UTC, merged